services:
    app:
        build: .
        env_file:
            - ./.env
        environment:
            - NODE_ENV=${APP_ENV}
        ports:
            - ${APP_PORT}:${APP_PORT}
            - "9229:9229"
        volumes:
            - ./src:/var/app/src
            - ./test:/var/app/test
            - ./package.json:/var/app/package.json
            - ./.env:/var/app/.env
            - ./configs:/var/app/configs
            - ./prisma:/var/app/prisma
            - ./tsconfig.json:/var/app/tsconfig.json
            - ./nest-cli.json:/var/app/nest-cli.json
            - ${HOST_ROUTE_KEYFILENAME}:/var/app/keyFilename.json
        depends_on:
            - database
        networks:
            - proveify-bridge
        command:
          - npm
          - run
          - start:debug
    database:
        image: mysql:8.0-debian
        env_file:
            - ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
        ports:
            - ${DB_PORT}:${DB_PORT}
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - proveify-bridge
volumes:
    mysql-data:
networks:
    proveify-bridge:
        driver: bridge