FROM node:22.13.1-alpine3.21 AS build

WORKDIR /var/app
COPY package.json .
RUN npm install
COPY . .

RUN npx prisma generate

RUN npm run build


FROM node:22.13.1-alpine3.21
ENV APP_PORT=3001
ENV APP_ENV=production

WORKDIR /var/app
COPY --from=build /var/app/dist /var/app
COPY --from=build /var/app/node_modules /var/app/node_modules

EXPOSE ${APP_PORT}

CMD ["node","src/main"]


