FROM node:22.13.1-alpine3.21 AS build

WORKDIR /var/app
COPY package.json .
RUN npm install
COPY . .

RUN npx prisma generate

RUN npm run build


FROM node:22.13.1-alpine3.21

WORKDIR /var/app
ENV APP_PORT=3001
ENV APP_ENV=production

COPY --from=build /var/app/dist ./dist
COPY --from=build /var/app/node_modules ./node_modules
COPY package*.json .

EXPOSE ${APP_PORT}

CMD ["node","dist/src/main"]


